using LabelsMis.Domain.Enums;

namespace LabelsMis.Domain.Estimating.Models;

public record EstimateRequest(
    decimal LabelAcrossIn,
    decimal LabelAroundIn,
    decimal CornerRadiusIn,
    decimal GutterAcrossIn,
    decimal GutterAroundIn,
    decimal BleedIn,
    Guid PressId,
    decimal PressWebWidthIn,
    decimal PressMaxImageWidthIn,
    decimal PressFrameRepeatIn,
    decimal PressMaxImageLengthIn,
    decimal PressEdgeMarginIn,
    decimal PressSetupMinutes,
    decimal PressCostPerHour,
    decimal PressSpeedFpm,
    bool PressClickBased,
    IndigoInkSet InkSet,
    decimal ClickRatePer1000,
    SpecialInkSpec? WhiteInk,
    SpecialInkSpec? SilverInk,
    Guid StockId,
    decimal StockWidthIn,
    decimal StockCostPerMsi,
    IReadOnlyList<FinishingOperationRequest> FinishingOperations,
    IReadOnlyList<int> Quantities,
    decimal SetupWasteImpressions,
    decimal RunningWastePct,
    decimal CustomerMarkupPct,
    decimal MinimumMarginPct,
    int? MaxLabelsAcrossOverride = null,
    LabelOrientation? LabelOrientationOverride = null);
